//! StatusNotifierItem (system tray) D-Bus server.
//!
//! Linux-only (`cfg(all(unix, not(target_os = "macos")))`). On
//! Windows / macOS the tray is implemented via native APIs in
//! follow-up PRs because the GTK-based `tray-icon` crate requires a
//! GTK event loop on the same thread the icon was created on, which
//! is incompatible with GPUI's main-thread model.
//!
//! ## Design
//!
//! Mirrors `src/mpris.rs` exactly:
//!
//! - A dedicated worker thread (`tempo-tray`) parks on
//!   `async_io::block_on` running ksni's async loop. ksni speaks
//!   `org.kde.StatusNotifierItem` over D-Bus directly; the panel /
//!   bar implementation in the user's compositor (Waybar tray
//!   module on Hyprland/Sway, Plasma's panel, GNOME's
//!   AppIndicator extension) is the SNI host that renders the icon
//!   and pops the menu on right-click.
//! - Two crossbeam channels glue the worker to the GPUI thread.
//!   `TrayCommand` flows worker → GPUI when the user clicks an
//!   icon / activates a menu item; `TrayUpdate` flows GPUI →
//!   worker when the now-playing state changes.
//! - The `TrayService::push_update` is non-blocking and side-effect-
//!   free, matching the style of `MprisService::push_update`.
//!
//! ## Tray-as-process-root
//!
//! By design the tray icon outlives the main window: closing the
//! window's X is intercepted in `main.rs` and minimizes instead
//! (see `lifecycle.rs`). The only path that actually exits Tempo
//! is the tray menu's "Quit Tempo" item, which fires
//! `TrayCommand::Quit` and the `dispatch_tray_command` handler in
//! `src/app/tray_panel.rs` calls `cx.quit()`.

use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::thread;
use std::time::Duration;

use anyhow::Result;
use crossbeam_channel::{Receiver, Sender};
use ksni::{Handle, Icon, Status, ToolTip, Tray, TrayMethods};

/// Commands generated by the tray host (compositor panel) that the
/// GPUI thread should apply to the in-app player. Drained in the
/// 50ms tick installed by `TempoApp::start_tray_service`.
#[derive(Clone, Debug)]
pub enum TrayCommand {
    /// User left-clicked the tray icon. Per
    /// freedesktop StatusNotifierItem semantics this means
    /// "primary action": for a media player that's "raise / show
    /// the main window".
    LeftClick,
    /// User middle-clicked the tray icon. We use this as a
    /// power-user shortcut for play/pause (matches the pattern of
    /// most Linux media-player tray icons).
    MiddleClick,
    /// User scrolled the wheel over the tray icon. `delta` follows
    /// freedesktop convention: positive = scroll up = volume up.
    Scroll {
        delta: i32,
    },
    /// "Show Tempo" menu item: bring the main window back from the
    /// tray. Same target as `LeftClick` but kept distinct in case
    /// we want to differentiate behaviour later.
    ShowWindow,
    /// "Hide Tempo" menu item: minimize the main window to the
    /// tray. Same target as the `HideWindow` GPUI action and the
    /// `Ctrl+Shift+H` keybinding.
    HideWindow,
    /// Transport menu items.
    PlayPause,
    Prev,
    Next,
    Random,
    /// "Quit Tempo" menu item. The dispatcher calls `cx.quit()`,
    /// which is the *only* path that actually exits the process
    /// (the X button on the main window minimizes instead).
    Quit,
}

/// Property updates pushed from the GPUI side to the tray runtime.
/// On receipt the runtime calls `Handle::update` so ksni rebuilds
/// the tooltip / menu / overlay-icon and broadcasts D-Bus property
/// changes to the tray host.
#[derive(Clone, Debug)]
pub enum TrayUpdate {
    /// New now-playing track, or `None` to clear ("Tempo — Idle").
    NowPlaying(Option<TrayTrackMeta>),
    /// Play/pause state, drives the tray-icon overlay glyph and
    /// the menu's "Play / Pause" label.
    PlayingState(bool),
    /// Window-visibility state. `true` = window is minimized to the
    /// tray (menu shows "Show Tempo"); `false` = window is visible
    /// (menu shows "Hide Tempo").
    WindowHidden(bool),
}

/// Now-playing payload mirrored to the tray. Title/artist/album
/// flow into the tray menu's three header rows and the tooltip.
#[derive(Clone, Debug, Default)]
pub struct TrayTrackMeta {
    pub title: String,
    pub artist: String,
    pub album: String,
}

/// Owns the tray runtime thread. Drop the service to shut the
/// D-Bus connection down cleanly.
pub struct TrayService {
    running: Arc<AtomicBool>,
    pub update_tx: Sender<TrayUpdate>,
}

impl TrayService {
    /// Boot the tray. Returns `Err` if the D-Bus session bus is
    /// unreachable; the GPUI side logs and continues without a
    /// tray icon (matches the fail-soft pattern of MPRIS).
    ///
    /// Note that the icon will only be visible if the user's
    /// desktop has an SNI host running. On Hyprland/Sway that
    /// means the Waybar `tray` module needs to be enabled. KDE
    /// Plasma's panel and GNOME with the AppIndicator extension
    /// also work out of the box.
    pub fn new() -> Result<(Self, Receiver<TrayCommand>)> {
        let running = Arc::new(AtomicBool::new(true));
        let (cmd_tx, cmd_rx) = crossbeam_channel::unbounded::<TrayCommand>();
        let (update_tx, update_rx) = crossbeam_channel::unbounded::<TrayUpdate>();

        let running_clone = running.clone();
        thread::Builder::new()
            .name("tempo-tray".into())
            .spawn(move || {
                async_io::block_on(run_tray_service(running_clone, cmd_tx, update_rx));
            })?;

        Ok((Self { running, update_tx }, cmd_rx))
    }

    /// Push an update to the tray. Cheap, never blocks.
    pub fn push_update(&self, update: TrayUpdate) {
        let _ = self.update_tx.send(update);
    }
}

impl Drop for TrayService {
    fn drop(&mut self) {
        self.running.store(false, Ordering::Release);
    }
}

// ---------------------------------------------------------------------------
// ksni `Tray` implementation.
// ---------------------------------------------------------------------------

/// All mutable state ksni needs to render the tray icon and menu.
/// Owned by the worker thread and only ever mutated through
/// `Handle::update` so ksni's diff/property-change machinery sees
/// every transition.
struct TempoTray {
    cmd_tx: Sender<TrayCommand>,
    track: Option<TrayTrackMeta>,
    is_playing: bool,
    /// Mirror of `TempoApp::window_hidden`. `true` when the main
    /// window has been minimized to the tray. Drives the menu's
    /// "Show Tempo" / "Hide Tempo" toggle.
    window_hidden: bool,
}

impl Tray for TempoTray {
    fn id(&self) -> String {
        "tempo".into()
    }

    fn title(&self) -> String {
        // Cosmetic; some hosts read this as the "application"
        // friendly name in the tray accessibility tree.
        "Tempo".into()
    }

    fn status(&self) -> Status {
        // `Active` makes the icon always visible. `Passive` hides
        // it on some hosts. We always want to be visible because
        // the tray is the only path back to the main window after
        // the user X-es it out.
        Status::Active
    }

    fn icon_name(&self) -> String {
        // Try to resolve a reasonable freedesktop name first; the
        // tray host falls through to `icon_pixmap` when it can't.
        // Picking a name from the standard icon naming spec means
        // most users get an on-theme glyph. For installs without
        // these names, the bundled pixmap below is the fallback.
        "multimedia-player".into()
    }

    fn icon_pixmap(&self) -> Vec<Icon> {
        // ARGB32 fallback. ksni's `Icon` has `width`, `height`,
        // and a `data: Vec<u8>` field where each pixel is four
        // bytes laid out big-endian as `A R G B`. We ship two
        // sizes for HiDPI panels.
        let mut out = Vec::new();
        if let Some(icon) = bundled_icon(22) {
            out.push(icon);
        }
        if let Some(icon) = bundled_icon(44) {
            out.push(icon);
        }
        out
    }

    fn overlay_icon_name(&self) -> String {
        // Render a tiny play/pause overlay so users can see
        // playback state at a glance from the panel without
        // hovering for a tooltip. Both names are in the standard
        // freedesktop icon naming spec.
        if self.is_playing {
            "media-playback-start".into()
        } else {
            String::new()
        }
    }

    fn tool_tip(&self) -> ToolTip {
        let (title, description) = match self.track.as_ref() {
            Some(track) => {
                let title = if track.title.is_empty() {
                    "Tempo".to_string()
                } else if track.artist.is_empty() {
                    track.title.clone()
                } else {
                    format!("{} — {}", track.title, track.artist)
                };
                let description = if track.album.is_empty() {
                    String::new()
                } else {
                    track.album.clone()
                };
                (title, description)
            }
            None => ("Tempo".to_string(), "No track loaded".to_string()),
        };
        ToolTip {
            icon_name: "multimedia-player".into(),
            icon_pixmap: Vec::new(),
            title,
            description,
        }
    }

    fn activate(&mut self, _x: i32, _y: i32) {
        let _ = self.cmd_tx.send(TrayCommand::LeftClick);
    }

    fn secondary_activate(&mut self, _x: i32, _y: i32) {
        let _ = self.cmd_tx.send(TrayCommand::MiddleClick);
    }

    fn scroll(&mut self, delta: i32, orientation: ksni::Orientation) {
        if !matches!(orientation, ksni::Orientation::Vertical) {
            return;
        }
        let _ = self.cmd_tx.send(TrayCommand::Scroll { delta });
    }

    fn menu(&self) -> Vec<ksni::MenuItem<Self>> {
        use ksni::MenuItem;
        use ksni::menu::{StandardItem, SubMenu};
        let mut items: Vec<MenuItem<Self>> = Vec::new();

        // Now-playing header rows. We render them as disabled
        // `StandardItem`s so they're visually present but not
        // clickable. The `SubMenu` form would be the "right" way
        // for hierarchical tray menus, but every tray host we
        // care about renders flat StandardItems just fine and
        // they're easier to read at a glance.
        //
        // The track title row is prefixed with a Unicode play
        // (▶) or pause (⏸) glyph so users can see the current
        // playback state at a glance from the menu, without
        // having to read the menu's "Play"/"Pause" label below
        // (which describes the *next* action, not the current
        // state). Most tray hosts (Plasma, Waybar's GTK menu)
        // render these glyphs cleanly. If a host doesn't have
        // glyph coverage they degrade to a fallback box rather
        // than breaking the menu.
        match self.track.as_ref() {
            Some(track) => {
                if !track.title.is_empty() {
                    let prefix = if self.is_playing { "▶  " } else { "⏸  " };
                    items.push(
                        StandardItem {
                            label: format!("{prefix}{}", track.title),
                            enabled: false,
                            ..Default::default()
                        }
                        .into(),
                    );
                }
                if !track.artist.is_empty() {
                    items.push(
                        StandardItem {
                            label: track.artist.clone(),
                            enabled: false,
                            ..Default::default()
                        }
                        .into(),
                    );
                }
                if !track.album.is_empty() {
                    items.push(
                        StandardItem {
                            label: track.album.clone(),
                            enabled: false,
                            ..Default::default()
                        }
                        .into(),
                    );
                }
                items.push(MenuItem::Separator);
            }
            None => {
                items.push(
                    StandardItem {
                        label: "Tempo — Idle".into(),
                        enabled: false,
                        ..Default::default()
                    }
                    .into(),
                );
                items.push(MenuItem::Separator);
            }
        }

        // Transport. Labels track is_playing so the user sees the
        // command they're about to execute, not the current state.
        items.push(
            StandardItem {
                label: if self.is_playing { "Pause" } else { "Play" }.into(),
                icon_name: if self.is_playing {
                    "media-playback-pause".into()
                } else {
                    "media-playback-start".into()
                },
                activate: Box::new(send(TrayCommand::PlayPause)),
                ..Default::default()
            }
            .into(),
        );
        items.push(
            StandardItem {
                label: "Previous".into(),
                icon_name: "media-skip-backward".into(),
                activate: Box::new(send(TrayCommand::Prev)),
                ..Default::default()
            }
            .into(),
        );
        items.push(
            StandardItem {
                label: "Next".into(),
                icon_name: "media-skip-forward".into(),
                activate: Box::new(send(TrayCommand::Next)),
                ..Default::default()
            }
            .into(),
        );
        items.push(
            StandardItem {
                label: "Shuffle".into(),
                icon_name: "media-playlist-shuffle".into(),
                activate: Box::new(send(TrayCommand::Random)),
                ..Default::default()
            }
            .into(),
        );

        items.push(MenuItem::Separator);
        // Visibility toggle: label and target command flip with
        // `window_hidden`. Restoration paths beyond the tray (left
        // click, MPRIS Raise, hotkey, taskbar) all funnel through
        // the same `set_window_hidden(false)` helper, so this label
        // stays in sync with the actual window state.
        if self.window_hidden {
            items.push(
                StandardItem {
                    label: "Show Tempo".into(),
                    icon_name: "view-restore".into(),
                    activate: Box::new(send(TrayCommand::ShowWindow)),
                    ..Default::default()
                }
                .into(),
            );
        } else {
            items.push(
                StandardItem {
                    label: "Hide Tempo".into(),
                    icon_name: "window-minimize".into(),
                    activate: Box::new(send(TrayCommand::HideWindow)),
                    ..Default::default()
                }
                .into(),
            );
        }
        items.push(MenuItem::Separator);
        items.push(
            StandardItem {
                label: "Quit Tempo".into(),
                icon_name: "application-exit".into(),
                activate: Box::new(send(TrayCommand::Quit)),
                ..Default::default()
            }
            .into(),
        );

        // Suppress the unused-variant warning ksni's `SubMenu`
        // generates for this binding when no submenu is built.
        let _ = std::marker::PhantomData::<SubMenu<Self>>;
        items
    }
}

/// Helper that returns a closure compatible with ksni's
/// `StandardItem::activate` field. Each menu item gets its own
/// `cmd_tx` clone so the runtime can fire commands from any item
/// without cross-borrow issues.
fn send(command: TrayCommand) -> impl Fn(&mut TempoTray) + Send + 'static {
    move |tray: &mut TempoTray| {
        let _ = tray.cmd_tx.send(command.clone());
    }
}

/// Generate a minimal placeholder ARGB32 pixmap on the fly. We ship
/// the asset code-side rather than as a bundled file because a
/// hand-rolled glyph that respects the "T on a circle" branding
/// stays in sync with future theme changes more easily than a
/// committed PNG would. Replace with `include_bytes!` of a designed
/// asset later.
fn bundled_icon(size: i32) -> Option<Icon> {
    if size <= 0 {
        return None;
    }
    let s = size as usize;
    let mut data = vec![0u8; s * s * 4];
    let center = (s as f32 - 1.0) / 2.0;
    let radius = center; // full-bleed circle
    let bar_width = (s as f32 * 0.18).max(2.0);
    let crossbar_height = (s as f32 * 0.18).max(2.0);
    let crossbar_y = s as f32 * 0.30;
    let bar_height = s as f32 * 0.55;
    for y in 0..s {
        for x in 0..s {
            let dx = x as f32 - center;
            let dy = y as f32 - center;
            let dist = (dx * dx + dy * dy).sqrt();
            let in_circle = dist <= radius;
            // Antialias the circle edge softly.
            let circle_alpha = if in_circle {
                ((radius - dist).clamp(0.0, 1.0) + 0.85).min(1.0)
            } else {
                0.0
            };
            // Vertical bar (centered) + horizontal crossbar at the
            // top form a stylized "T".
            let bar_dx = (x as f32 - center).abs();
            let in_vertical_bar = bar_dx <= bar_width / 2.0
                && (y as f32) >= crossbar_y
                && (y as f32) <= crossbar_y + bar_height;
            let in_crossbar = (y as f32 >= crossbar_y - crossbar_height / 2.0)
                && (y as f32 <= crossbar_y + crossbar_height / 2.0)
                && bar_dx <= s as f32 * 0.32;
            let glyph = in_vertical_bar || in_crossbar;
            let i = (y * s + x) * 4;
            // ksni `Icon::data` is ARGB32 in network byte order
            // (big-endian per the StatusNotifierItem spec). We
            // emit `[A, R, G, B]` per pixel.
            let alpha = (circle_alpha * 255.0) as u8;
            if glyph && in_circle {
                // Glyph: light foreground.
                data[i] = alpha; // A
                data[i + 1] = 0xF5; // R
                data[i + 2] = 0xF5; // G
                data[i + 3] = 0xF7; // B
            } else if in_circle {
                // Background: theme-neutral dark teal/charcoal so
                // the icon reads on both light and dark panels.
                data[i] = alpha;
                data[i + 1] = 0x1F;
                data[i + 2] = 0x2A;
                data[i + 3] = 0x3A;
            } else {
                data[i] = 0;
                data[i + 1] = 0;
                data[i + 2] = 0;
                data[i + 3] = 0;
            }
        }
    }
    Some(Icon {
        width: size,
        height: size,
        data,
    })
}

// ---------------------------------------------------------------------------
// Worker thread entry point.
// ---------------------------------------------------------------------------

/// Builds the SNI registration, then alternates between draining the
/// `TrayUpdate` channel and yielding to ksni's async runtime so D-Bus
/// gets serviced. Same pattern as `mpris.rs::run_mpris_server`.
async fn run_tray_service(
    running: Arc<AtomicBool>,
    cmd_tx: Sender<TrayCommand>,
    update_rx: Receiver<TrayUpdate>,
) {
    let tray = TempoTray {
        cmd_tx,
        track: None,
        is_playing: false,
        window_hidden: false,
    };
    let handle: Handle<TempoTray> = match tray.spawn().await {
        Ok(handle) => handle,
        Err(error) => {
            crate::perf::event("tray.spawn_failed", format!("err={error}"));
            return;
        }
    };

    crate::perf::event("tray.started", "");

    while running.load(Ordering::Acquire) {
        // Drain pending updates.
        loop {
            match update_rx.try_recv() {
                Ok(update) => apply_update(&handle, update).await,
                Err(crossbeam_channel::TryRecvError::Empty) => break,
                Err(crossbeam_channel::TryRecvError::Disconnected) => {
                    crate::perf::event("tray.disconnect", "update_rx");
                    handle.shutdown();
                    return;
                }
            }
        }
        async_io::Timer::after(Duration::from_millis(50)).await;
    }

    handle.shutdown();
    crate::perf::event("tray.exit", "");
}

async fn apply_update(handle: &Handle<TempoTray>, update: TrayUpdate) {
    match update {
        TrayUpdate::NowPlaying(meta) => {
            handle
                .update(move |tray| {
                    tray.track = meta;
                })
                .await;
        }
        TrayUpdate::PlayingState(is_playing) => {
            handle
                .update(move |tray| {
                    tray.is_playing = is_playing;
                })
                .await;
        }
        TrayUpdate::WindowHidden(hidden) => {
            handle
                .update(move |tray| {
                    tray.window_hidden = hidden;
                })
                .await;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_icon_dimensions_match() {
        let icon = bundled_icon(22).expect("22-px icon");
        assert_eq!(icon.width, 22);
        assert_eq!(icon.height, 22);
        assert_eq!(icon.data.len(), 22 * 22 * 4);
    }

    #[test]
    fn bundled_icon_rejects_zero_size() {
        assert!(bundled_icon(0).is_none());
        assert!(bundled_icon(-1).is_none());
    }
}
